### ISSUE TITLE
Build failed - sun.security.validator.ValidatorException: PKIX path building failed

### ISSUE THREAD

**Issue by spaam578** [CoreXDevelopmentTeam/NovaMobs#77]
Build failes while resolving dependencies:

Downloading: http://ci.regularbox.com/plugin/repository/everything/cn/nukkit/nukkit/1.0-SNAPSHOT/nukkit-1.0-20170826.101610-564.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project MobPlugin: Could not resolve dependencies for project cn.nukkit:MobPlugin:jar:1.1dev: Failed to collect dependencies at cn.nukkit:nukkit:jar:1.0-SNAPSHOT: Failed to read artifact descriptor for cn.nukkit:nukkit:jar:1.0-SNAPSHOT: Could not transfer artifact cn.nukkit:nukkit:pom:1.0-20170826.101610-564 from/to nukkit-repo (http://ci.regularbox.com/plugin/repository/everything/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR]

**Comment by Kirito-Kazuto** [comment]
plz use the circleci build

**Comment by Kirito-Kazuto** [comment]
@spaam578
