### ISSUE TITLE
Circle CI Boom

### ISSUE THREAD

**Issue by lsw46** [CoreXDevelopmentTeam/NovaMobs#78]
Title

**Comment by Kirito-Kazuto** [comment]
more info plz circle ci works fine

**Comment by Kirito-Kazuto** [comment]
@lsw46

**Comment by lsw46** [comment]
@Kirito-Kazuto ok 
thanks!

**Comment by lsw46** [comment]
I think I need to update README

**Comment by PikyCZ** [comment]
But link for download NovaMobs from CircleCi is in Readme

**Comment by lsw46** [comment]
@PikyCZ 
![image](https://user-images.githubusercontent.com/16436412/30486294-a526d4ce-9a62-11e7-8c41-1c42cd88fe4e.png)
